import AdminNavbar from "@/components/nav/Nav";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Admin Dashboard - Skepthegame",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <AdminNavbar>{children}</AdminNavbar>;
}
